# Generated by Django 2.2.19 on 2022-11-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cross',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
                ('ten', models.IntegerField()),
                ('fifteen', models.IntegerField()),
                ('twenty', models.IntegerField()),
                ('twentyfive', models.IntegerField()),
                ('thirtyfive', models.IntegerField()),
            ],
        ),
    ]
