# Generated by Django 2.2.19 on 2022-11-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cross',
            name='thirty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cross',
            name='name',
            field=models.CharField(max_length=5),
        ),
    ]
