# Generated by Django 2.2.19 on 2022-11-18 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0005_auto_20221116_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mmr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('one', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('two', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('three', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AddConstraint(
            model_name='mmr',
            constraint=models.CheckConstraint(check=models.Q(('one__gte', 0), ('two__gte', 0), ('three__gte', 0)), name='fields not minus'),
        ),
    ]
