# Generated by Django 2.2.16 on 2022-12-28 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0007_auto_20221118_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('ten', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('fifteen', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('twenty', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('twentyfive', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('thirty', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('thirtyfive', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AddConstraint(
            model_name='statistic',
            constraint=models.CheckConstraint(check=models.Q(('ten__gte', 0), ('fifteen__gte', 0), ('twenty__gte', 0), ('twentyfive__gte', 0), ('thirty__gte', 0), ('thirtyfive__gte', 0)), name='fields not minus'),
        ),
    ]
