# Generated by Django 2.2.16 on 2023-01-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0009_new_stat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_stat',
            old_name='lenght',
            new_name='length',
        ),
    ]
