# Generated by Django 2.2.16 on 2023-01-13 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0011_auto_20230110_1745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='new_stat',
            new_name='History',
        ),
    ]
